name: streamix_tv
description: تطبيق IPTV عصري وآمن
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^0.13.6
  better_player_plus: 1.0.8
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2
  video_player: ^2.11.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png

